version: "2"
services:
  monit:
    build: .
    pull_policy: build
    container_name: mmonit
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      #- MMONIT_LICENSE_OWNER="Fred"
      #- MMONIT_LICENSE_KEY="<M/Monit license key>"
    volumes:
      - mmonit_data:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9292:8080
    restart: unless-stopped
volumes:
  mmonit_data:
    external: true
